# Select image from https://hub.docker.com/_/php/
image: php:5.6

# Select what we should cache
#cache:
#  paths:
#  - vendor/

# prepare gitlab-ci
before_script:
- bash shell/gitlab-ci-setup.sh

# include services
services:
#- mysql

# define types/stages
types:
- build
- cleanup_build
- test
- deploy
- cleanup

# define jobs

# build job
build_job:
  type: build
  script:
  - bash echo "building ..."
  - bash pwd

# testing with php 5.x job
test_php5:
  type: test
  image: php:5.6
  script:
  - bash echo "testing php5.x ..."
  - bash pwd
  - phpunit --configuration tests/phpunit.xml --coverage-text
  allow_failure: false

# testing with php 7.x job
test_php7:
  type: test
  image: php:7.0
  script:
  - bash echo "testing php7.x ..."
  - bash pwd
  - phpunit --configuration tests/phpunit.xml --coverage-text
  allow_failure: false

# deploy job
deploy_job:
  type: deploy
  script:
  - bash echo "deploying ..."
  - pwd

# clean up job
cleanup_job:
  type: cleanup
  script:
  - bash echo "clean up after builds ..."
  - bash pwd
  #when: always

