# shell-runner configuration

# prepare gitlab-ci
before_script:
- shell/gitlab-ci-setup.sh
- php -d memory_limit=-1 composer.phar install

# include services
# define types/stages
types:
- test
- build
- deploy
- cleanup

# define jobs

# testing with php 5.x jobs
test-php5_job:
  type: test
  image: php:5.6
  script:
  - echo "testing application-base php-5.6 ..."
  - php vendor/bin/phpunit --version
  - php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./module/Application/test/phpunit.xml --coverage-text
  #- php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./vendor/my-application/module-admin/tests/phpunit.xml --coverage-text
  #- php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./vendor/my-application/module-twbs-api/tests/phpunit.xml --coverage-text
  allow_failure: false

# testing with php 7.x jobs
#test-php7_job:
#  type: test
#  image: php:7.0
#  script:
#  - echo "testing application-base php-7.0 ..."
#  - php vendor/bin/phpunit --version
#  - php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./module/Application/test/phpunit.xml --coverage-text
#  #- php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./vendor/my-application/module-admin/tests/phpunit.xml --coverage-text
#  #- php vendor/bin/phpunit -d memory_limit=-1 -vvv --configuration ./vendor/my-application/module-twbs-api/tests/phpunit.xml --coverage-text
#  allow_failure: false

# build job
build_job:
  type: build
  script:
  - shell/gitlab-ci-setup.sh
  - echo "building ..."
  - php ./vendor/bin/phpunit.phar --version
  allow_failure: false

# build job
#deploy_job:
#  type: build
#  script:
#  - echo "deploying ..."
#  - pwd
#  - php -v

# clean up job
#cleanup_whatever_is_left_job:
#  type: cleanup
#  script:
#  - echo "clean up after builds ..."
#  #when: always

