# shell-runner configuration

# prepare gitlab-ci
before_script:
- shell/gitlab-ci-setup.sh
- php -d memory_limit=-1 composer.phar install

# include services
# define types/stages
types:
- test
- build
- deploy
- cleanup

# define jobs

# testing with php 5.x jobs
#test-php5_job:
#  type: test
#  image: php:5.6
#  script:
#  - echo "testing application-base php-5.6 ..."
#  - ./phpunit -d memory_limit=-1 --colors --debug --configuration ./module/Application/test/phpunit.xml --coverage-text
#  allow_failure: false

# build job
build_job:
  type: build
  script:
  - shell/gitlab-ci-setup.sh
  - echo "building ..."
  - ./phpunit -d memory_limit=-1 --colors --debug --configuration ./module/Application/test/phpunit.xml --coverage-text
  allow_failure: false
