# shell-runner configuration

# prepare gitlab-ci
before_script:
- shell/gitlab-ci-setup.sh
- php -d memory_limit=-1 composer.phar install
- cp config/autoload/database.local.dist.php config/autoload/database.local.php
- echo 'DB... $MYSQL_USER @ $MYSQL_HOST'
- replace "_MYSQL_HOST_" "$MYSQL_HOST" -- config/autoload/database.local.php
- replace "_MYSQL_DATABASE_" "$MYSQL_DATABASE" -- config/autoload/database.local.php
- replace "_MYSQL_USER_" "$MYSQL_USER" -- config/autoload/database.local.php
- replace "_MYSQL_PASSWORD_" "$MYSQL_PASSWORD" -- config/autoload/database.local.php

# include services
# define types/stages
types:
- test
- build
- deploy
- cleanup

# define jobs

# testing with php 5.x jobs
test-php5_job:
  type: test
  image: php:5.6
  script:
#  - echo "testing application-base php-5.6 ..."
  - php -d memory_limit=-1 ./phpunit --colors --debug --configuration ./module/Application/test/phpunit.xml --coverage-text
  allow_failure: false

# build job
build_job:
  type: build
  script:
#  - shell/gitlab-ci-setup.sh
  - echo "building ..."
  - php -d memory_limit=-1 ./phpunit --colors --debug --configuration ./module/Application/test/phpunit.xml --coverage-text
  allow_failure: false

