# shell-runner configuration

# prepare gitlab-ci
#before_script:
#- bash shell/gitlab-ci-setup.sh

# include services
# define types/stages
types:
- test
- build
- deploy
- cleanup

# define jobs

# testing with php 5.x jobs
test-php5_job:
  type: test
  image: php:5.6
  script:
  - shell/gitlab-ci-setup.sh
  - echo "testing application-base php-5.6 ..."
  - php -v
  - pwd
  - ./phpunit -d memory_limit=-1 -v --configuration ./module/Application/test/phpunit.xml --coverage-text
  - ./phpunit -d memory_limit=-1 -v --configuration ./vender/my-application/module-admin/tests/phpunit.xml --coverage-text
  - ./phpunit -d memory_limit=-1 -v --configuration ./vender/my-application/module-twbs-api/tests/phpunit.xml --coverage-text
  allow_failure: false

# testing with php 7.x jobs
test-php7_job:
  type: test
  image: php:7.0
  script:
  - shell/gitlab-ci-setup.sh
  - echo "testing application-base php-7.0 ..."
  - php -v
  - pwd
  - ./phpunit -d memory_limit=-1 -v --configuration ./module/Application/test --coverage-text/phpunit.xml
  - ./phpunit -d memory_limit=-1 -v --configuration ./vender/my-application/module-admin/tests/phpunit.xml --coverage-text
  - ./phpunit -d memory_limit=-1 -v --configuration ./vender/my-application/module-twbs-api/tests/phpunit.xml --coverage-text
  allow_failure: false

# build job
build_job:
  type: build
  script:
  - shell/gitlab-ci-setup.sh
  - echo "building ..."
  - pwd
  - php -v
  allow_failure: false

# build job
#deploy_job:
#  type: build
#  script:
#  - echo "deploying ..."
#  - pwd
#  - php -v

# clean up job
cleanup_whatever_is_left_job:
  type: cleanup
  script:
  - echo "clean up after builds ..."
  - pwd
  #when: always

