# Select image from https://hub.docker.com/_/php/
image: php:5.6

services:
- cache
- mysql

# Select what we should cache
cache:
  paths:
  - vendor/

# prepare gitlab-ci
before_script:
- bash shell/gitlab-ci-setup.sh

# include services
# define types/stages
types:
- build
- cleanup_build
- test
- deploy
- cleanup

# define jobs

# build job
build_job:
  type: build
  script:
  - echo "building ..."
  - pwd
  - php -v

# testing with php 5.x job
test_php5:
  type: test
  image: php:5.6
  script:
  - echo "testing php5.x ..."
  - php -v
  - pwd
  - php ./phpunit -d memory_limit=-1 -v --configuration ./module/Application/test/phpunit.xml --coverage-text
  allow_failure: false

# testing with php 7.x job
test_php7:
  type: test
  image: php:7.0
  script:
  - echo "testing php7.x ..."
  - php -v
  - pwd
  - php ./phpunit -d memory_limit=-1 -v --configuration ./module/Application/test/phpunit.xml --coverage-text
  allow_failure: false

# deploy job
deploy_job:
  type: deploy
  script:
  - echo "deploying ..."
  - pwd

# clean up job
cleanup_job:
  type: cleanup
  script:
  - echo "clean up after builds ..."
  - pwd
  #when: always

