<?php
namespace ApplicationTest\Controller;

use \Application\Controller\IndexController,
	\ApplicationTest\Bootstrap as AppTestsBootstrap,
    Zend\Http\Request,
    Zend\Http\Response,
    Zend\Mvc\MvcEvent,
    Zend\Mvc\Router\RouteMatch,
	Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-10 at 22:17:42.
 */
class BaseActionControllerTest extends AbstractHttpControllerTestCase
{
    /**
     * @var BaseActionController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp()
    {
        $this->controller	= new BaseController();
		$this->controller->setServiceLocator(AppTestsBootstrap::getServiceManager());
		$this->request		= new Request();
		//$this->routeMatch	= new RouteMatch(array('controller' => 'index'));
		$this->event		= new MvcEvent();
		$this->event->setRouteMatch($this->routeMatch);
		$this->controller->setEvent($this->event);
		$this->object		= new BaseActionController;
    	$this->setApplicationConfig(
            include './config/application.config.php'
        );
        parent::setUp();
    }
    
    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
