<?php
namespace ApplicationTest\Controller;

use \Application\Controller\IndexController,
    Zend\Http\Request,
    Zend\Http\Response,
    Zend\Mvc\MvcEvent,
    Zend\Mvc\Router\RouteMatch,
	Zend\Test\PHPUnit\Controller\AbstractHttpControllerTestCase;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-10 at 23:14:37.
 */
class IndexControllerTest extends AbstractHttpControllerTestCase
{
	
	/**
	 * @var \Application\Controller\IndexController
	 */
	protected $object;

	/**
	 * @var \Application\Controller\IndexController
	 */
	protected $controller;
	
	/**
	 * @var \Zend\Http\Request
	 */
	protected $request;
	
	/**
	 * @var \Zend\Http\Response
	 */
	protected $response;
	
	/**
	 * @var \Zend\Mvc\Router\RouteMatch
	 */
	protected $routeMatch;
	
	/**
	 * @var \Zend\Mvc\MvcEvent
	 */
	protected $event;
 

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setUp()
	{
		$this->setApplicationConfig(
			include './config/application.config.php'
		);
		parent::setUp();
		$this->controller	= new IndexController();
		$this->controller->setServiceLocator($this->getApplicationServiceLocator());
		$this->request		= new Request();
		$this->routeMatch	= new RouteMatch(array('controller' => 'index'));
		$this->event		= new MvcEvent();
		$this->event->setRouteMatch($this->routeMatch);
		$this->controller->setEvent($this->event);
		$this->object		= new IndexController;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown()
	{
	}
	
	/**
	 * is the action dispatchable per route setting ?
	 */
	public function testIndexActionCanBeDispatchedByRoute()
	{
		$this->dispatch('/');
		$this->assertResponseStatusCode(200);
	
		$this->assertModuleName('Application');
		$this->assertControllerName('Application\Controller\Index');
		$this->assertControllerClass('IndexController');
		$this->assertMatchedRouteName('home');
	}

	/**
	 * is the action accessable per request/response action name ?
	 */
	public function testIndexActionCanBeDispatchedByAction()
	{
		// Specify which action to run
		$this->routeMatch->setParam('action', 'index');
		//$this->routeMatch->setParam('type', 'mvc');
		
		// Kick the controller into action
		$result = $this->controller->dispatch($this->request);
	
		// Check the HTTP response code
		$response = $this->controller->getResponse();
		$this->assertEquals(200, $response->getStatusCode());
	
		// Check for a ViewModel to be returned
		$this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
	
		// Test the parameters contained in the View model
		//$vars = $result->getVariables();
		//$this->assertTrue(isset($vars['var']));
	}
	
	public function test404()
	{
		$this->routeMatch->setParam('action', 'not-implemented-yet');
		$this->routeMatch->setParam('type', 'mvc');
		$result = $this->controller->dispatch($this->request);
		$response = $this->controller->getResponse();
		$this->assertEquals(404, $response->getStatusCode());
	}
	
}
