<?php
namespace ApplicationTest\Controller;

use \Application\Controller\SetupController,
    Zend\Http\Request,
    Zend\Http\Response,
    Zend\Mvc\MvcEvent,
    Zend\Mvc\Router\RouteMatch
;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-10 at 23:14:46.
 */
class SetupControllerTest extends BaseActionControllerTest
{
	
	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	public function setupController()
	{
		$this->controller	= new SetupController();
		$this->controller->setServiceLocator($this->getApplicationServiceLocator());
		$this->routeMatch	= new RouteMatch(array('controller' => 'setup'));
		$this->controller->setEvent($this->event);
	}
	
	/**
	 * is the action dispatchable per route setting ?
	 */
	public function testIndexActionCanBeDispatchedByRoute()
	{
		$this->dispatch('/setup/');
		$this->assertResponseStatusCode(200);
	
		$this->assertModuleName('Application');
		$this->assertControllerName('Application\Controller\Setup');
		$this->assertControllerClass('SetupController');
		$this->assertMatchedRouteName('setup');
	}

	/**
	 * is the action accessable per request/response action name ?
	 */
	public function testIndexActionCanBeDispatchedByAction()
	{
		// Specify which action to run
		$this->routeMatch->setParam('action', 'index');
	
		// Kick the controller into action
		$result = $this->controller->dispatch($this->request);
	
		// Check the HTTP response code
		$response = $this->controller->getResponse();
		$this->assertEquals(200, $response->getStatusCode());
	
		// Check for a ViewModel to be returned
		$this->assertInstanceOf('Zend\View\Model\ViewModel', $result);
	
		// Test the parameters contained in the View model
		//$vars = $result->getVariables();
		//$this->assertTrue(isset($vars['var']));
	}
	
	public function test404()
	{
		$this->routeMatch->setParam('action', 'not-implemented-yet');
		$result = $this->controller->dispatch($this->request);
		$response = $this->controller->getResponse();
		$this->assertEquals(404, $response->getStatusCode());
	}
	
}