<pre class="debuginfo">
<strong>Module:</strong>     Admin &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Rolle entfernen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<p><?php echo $this->translate("Rolle wirklich entfernen?"); ?></p>
		<p>
			'<?php echo $this->escapeHtml($aclrole->rolename); ?>' - 
			'<?php echo $this->escapeHtml($aclrole->roleslug); ?>'?
		</p>
		<?php
		$url = $this->url('admin/acledit', array(
		    'action'	=> 'deleterole',
		    'acl_id'	=> (int)$acl_id,
		));
		?>
		<form action="<?php echo $url; ?>" method="post">
			<div>
				<input type="hidden" name="id" value="<?php echo (int)$acl_id; ?>" />
				<input type="submit" name="del" value="<?php echo $this->translate("entfernen"); ?>" />
				<input type="submit" name="abort" value="<?php echo $this->translate("abbrechen"); ?>" />
			</div>
		</form>
	</div>
</div>
	
