		<h4 class="hide"><?php echo $this->translate("Listen-Ansicht")?></h4>
		
		<table class="table list hide">
			<tr>
			    <th><?php echo $this->translate("Rolle")?></th>
			    <th><?php echo $this->translate("Resource")?></th>
			    <th><?php echo $this->translate("Status")?></th>
			    <th>&nbsp;</th>
			</tr>
			<?php foreach ($resources as $resource) : ?>
				<?php foreach ($roles as $role) : ?>
				<?php
					$acl = $acltable->getAclByRoleResource($role['aclroles_id'],$resource['aclresources_id']);
				?>
				<tr>
			    <td><?php echo $this->escapehtml($role['roleslug']) ?></td>
			    <td><?php echo $this->escapehtml($resource['resourceslug']) ?></td>
			    <td><?php echo (!empty($acl->state) ? $this->escapehtml($acl->state) : '---') ?></td>
			    <td>
			        <a href="<?php echo $this->url('admin/acledit',
			            array('action'=>'edit', 'acl_id' => $acl->acl_id));?>"><?php echo $this->translate("ändern"); ?></a>
			        <a href="<?php echo $this->url('admin/acledit',
			            array('action'=>'delete', 'acl_id' => $acl->acl_id));?>"><?php echo $this->translate("entfernen"); ?></a>
			    </td>
				</tr>
				<?php endforeach; ?>
			<?php endforeach; ?>
			
			<!--
			<?php foreach ($acldata as $acl) : ?>
			<?php 
				$role = $Aclrole->getAclrole($acl->aclroles_id); 
				$resource = $Aclresource->getAclresource($acl->aclresources_id); 
			?>
			<tr>
			    <td><?php echo $this->escapeHtml($role->rolename);?></td>
			    <td><?php echo $this->escapeHtml($resource->resourcename);?></td>
			    <td><?php echo $this->escapeHtml($acl->state);?></td>
			    <td>
			        <a href="<?php echo $this->url('admin/acledit',
			            array('action'=>'edit', 'acl_id' => $acl->acl_id));?>"><?php echo $this->translate("ändern"); ?></a>
			        <a href="<?php echo $this->url('admin/acledit',
			            array('action'=>'delete', 'acl_id' => $acl->acl_id));?>"><?php echo $this->translate("entfernen"); ?></a>
			    </td>
			</tr>
			<?php endforeach; ?>
			-->
		</table>
