<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ApplicationTest\ApplicationTest'                     => __DIR__ . '/test/ApplicationTest/ApplicationTest.php',
    'ApplicationTest\Bootstrap'                           => __DIR__ . '/test/bootstrap.php',
    'ApplicationTest\Controller\BaseActionControllerTest' => __DIR__ . '/test/ApplicationTest/Controller/BaseActionControllerTest.php',
    'ApplicationTest\Controller\IndexControllerTest'      => __DIR__ . '/test/ApplicationTest/Controller/IndexControllerTest.php',
    'ApplicationTest\Controller\SetupControllerTest'      => __DIR__ . '/test/ApplicationTest/Controller/SetupControllerTest.php',
    'ApplicationTest\Controller\SystemControllerTest'     => __DIR__ . '/test/ApplicationTest/Controller/SystemControllerTest.php',
    'ApplicationTest\Framework\ActionControllerTestCase'  => __DIR__ . '/test/ApplicationTest/Framework/ActionControllerTestCase.php',
    'ApplicationTest\Framework\TestCase'                  => __DIR__ . '/test/ApplicationTest/Framework/TestCase.php',
    'ApplicationTest\Model\DbStructUpdaterTest'           => __DIR__ . '/test/ApplicationTest/Model/DbStructUpdaterTest.php',
    'Application\Controller\BaseActionController'         => __DIR__ . '/src/Application/Controller/BaseActionController.php',
    'Application\Controller\IndexController'              => __DIR__ . '/src/Application/Controller/IndexController.php',
    'Application\Controller\JsonResultController'         => __DIR__ . '/src/Examples/Controller/JsonResultController.php',
    'Application\Controller\SetupController'              => __DIR__ . '/src/Application/Controller/SetupController.php',
    'Application\Controller\SystemController'             => __DIR__ . '/src/Application/Controller/SystemController.php',
    'Application\Model\DbStructUpdater'                   => __DIR__ . '/src/Application/Model/DbStructUpdater.php',
    'Application\Module'                                  => __DIR__ . '/Module.php',
    'MyListener'                                          => __DIR__ . '/test/MyListener.php',
);
