<?php 
/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
$oBootstrap = $this->Bootstrap();
/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
$oComponents = $this->Components();
/** @var \Admin\Entity\User $user **/
$oUser = $this->zfcUserIdentity();

$messages = $this->flashMessenger()->renderCurrent('error', array('error alert alert-error'));
$messages .= $this->flashMessenger()->renderCurrent('warning', array('warning alert alert-warning'));
$messages .= $this->flashMessenger()->renderCurrent('success', array('success alert alert-success'));
$messages .= $this->flashMessenger()->renderCurrent('info', array('info alert alert-info'));
$this->flashMessenger()->getPluginFlashMessenger()->clearCurrentMessagesFromContainer();

$modalLayout = $oComponents->Modal()
	->setHeader( (isset($this->title) ? $this->title : "") )
	->setContent(
		array(
			'tagname' => 'div',
			'classnames' => 'modal-body alert-wrap',
			'content' => $messages . $this->content,
		)
	)
;

echo $modalLayout . $this->inlineScript();
