<pre class="debuginfo">
<strong>Module:</strong>     Users &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Neuen Benutzer hinzufügen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('user_id'));
			echo $this->formRow($form->get('username'));
			echo $this->formRow($form->get('email'));
			echo $this->formRow($form->get('display_name'));
			echo $this->formRow($form->get('password'));
			echo '<hr />';
			echo $this->formRow($form->get('aclrole'));
			echo '<hr />';
			echo $this->formRow($form->get('state'));
			echo '<hr />';
			echo $this->formSubmit($form->get('submit'));
			echo $this->formReset($form->get('reset'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>
