<pre class="debuginfo">
<strong>Module:</strong>     Users &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Neuen Benutzer hinzufügen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php 
			$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form); ?>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('username')); ?>
				<?php echo $this->formInput($form->get('username')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('email')); ?>
				<?php echo $this->formInput($form->get('email')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('display_name')); ?>
				<?php echo $this->formInput($form->get('display_name')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('password')); ?>
				<?php echo $this->formInput($form->get('password')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<hr />
			<div class="form-group">
				<?php echo $this->formLabel($form->get('street')); ?>
				<?php echo $this->formInput($form->get('street')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('city')); ?>
				<?php echo $this->formInput($form->get('city')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('phone')); ?>
				<?php echo $this->formInput($form->get('phone')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<hr />
			<div class="form-group">
				<?php echo $this->formLabel($form->get('aclrole')); ?>
				<?php echo $this->formSelect($form->get('aclrole')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<hr />
			<div class="form-group">
				<?php echo $this->formLabel($form->get('state')); ?>
				<?php echo $this->formSelect($form->get('state')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('user_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
		<?php echo $this->form()->closeTag($form); ?>
		<?php
			/*$form->setAttribute('action', $this->url('admin/default', array('controller' => 'users', 'action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('user_id'));
			echo $this->formRow($form->get('username'));
			echo $this->formRow($form->get('email'));
			echo $this->formRow($form->get('display_name'));
			echo $this->formRow($form->get('password'));
			echo '<hr />';
			echo $this->formRow($form->get('aclrole'));
			echo '<hr />';
			echo $this->formRow($form->get('state'));
			echo '<hr />';
			echo $this->formSubmit($form->get('submit'));
			echo $this->formReset($form->get('reset'));
			echo $this->form()->closeTag();*/
		?>
	</div>
</div>
