<pre class="debuginfo">
<strong>Module:</strong>     Users &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Benutzer-Daten bearbeiten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url(
			    'admin/default',
			    array(
			        'controller'	=> 'users',
			        'action'		=> 'edit',
			        'user_id'		=> $this->user_id,
			    )
			));
			$form->prepare();
		
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('user_id'));
			echo $this->formRow($form->get('display_name'));
			echo $this->formRow($form->get('username'));
			echo $this->formRow($form->get('email'));
			echo $this->formRow($form->get('password'));
			echo '<hr />';
			echo $this->formRow($form->get('street'));
			echo $this->formRow($form->get('city'));
			echo $this->formRow($form->get('phone'));
			echo '<hr />';
			echo $this->formRow($form->get('state'));
			echo $this->formRow($form->get('aclrole'));
			echo '<hr />';
			echo $this->formSubmit($form->get('submit'));
			echo $this->formReset($form->get('reset'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>
