<pre class="debuginfo">
<strong>Module:</strong>     Users &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="navbar-subnav">
    <a href="<?php echo $this->url('admin/default', array('controller'=>'users', 'action'=>'add'));?>"><?php echo $this->translate("Neuen Benutzer hinzufügen")?></a>
</div>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Benutzer verwalten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		
		<table class="table">
			<tr>
			    <th><?php echo $this->translate("Username")?></th>
			    <th><?php echo $this->translate("E-Mail")?></th>
			    <th><?php echo $this->translate("Rolle")?></th>
			    <th>&nbsp;</th>
			</tr>
			<?php foreach ($userdata as $user) : ?>
			<tr>
			    <td><?php echo $this->escapeHtml($user->username);?></td>
			    <td><?php echo $this->escapeHtml($user->email);?></td>
			    <td><?php echo $this->escapeHtml($user->aclrole);?></td>
			    <td>
			        <a href="<?php echo $this->url('admin/default',
			            array('controller'=>'users', 'action'=>'edit', 'user_id' => $user->user_id));?>"><?php echo $this->translate("ändern"); ?></a>
			        <a href="<?php echo $this->url('admin/default',
			            array('controller'=>'users', 'action'=>'delete', 'user_id' => $user->user_id));?>"><?php echo $this->translate("entfernen"); ?></a>
			    </td>
			</tr>
			<?php endforeach; ?>
		</table>
	<?php echo $this->output ?>
	</div>
</div>
