<pre class="debuginfo">
<strong>Module:</strong>     Admin\Settings &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Neuen Benutzer hinzufügen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php echo $this->form()->openTag($form); ?>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('type')); ?>
				<?php echo $this->formInput($form->get('type')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('name')); ?>
				<?php echo $this->formInput($form->get('name')); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('value')); ?>
				<?php echo $this->formInput($form->get('value')); ?>
			</div>
			<?php echo $this->formHidden($form->get('settings_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn'))); ?>
		<?php echo $this->form()->closeTag($form); ?>
		
		<?php
			$form->setAttribute('action', $this->url('admin/settingsedit', array('action' => 'add')));
			$form->prepare();
			
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('settings_id'));
			echo $this->formRow($form->get('type'));
			echo $this->formRow($form->get('name'));
			echo $this->formRow($form->get('value'));
			echo '<hr />';
			echo $this->formSubmit($form->get('submit'));
			echo $this->formReset($form->get('reset'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>
