<pre class="debuginfo">
<strong>Module:</strong>     Settingss &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Einstellung entfernen"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<p><?php echo $this->translate("Diese Einstellung wirklich entfernen?"); ?>:</p>
		<p><strong>
			'<?php echo $this->escapeHtml($settings->type); ?>' - 
			'<?php echo $this->escapeHtml($settings->name); ?>'?
		</strong></p>
		
		<?php
		$url = $this->url('admin/settingsedit', array(
		    'action'     => 'delete',
		    'set_id'         => $settings->settings_id,
		));
		?>
		<form action="<?php echo $url; ?>" method="post">
			<div class="form-group">
				<input type="hidden" name="id" value="<?php echo (int) $settings->settings_id; ?>" />
				<input class="btn btn-default" type="submit" name="del" value="<?php echo $this->translate("entfernen"); ?>" />
				<input class="btn btn-default" type="submit" name="abort" value="<?php echo $this->translate("abrechen"); ?>" />
			</div>
		</form>
	</div>
</div>
	
