<pre class="debuginfo">
<strong>Module:</strong>     Admin\Settings &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Einstellung bearbeiten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url(
			    'admin/settingsedit',
			    array(
			        'action'		=> 'edit',
			        'set_id'		=> $this->settings_id,
			    )
			));
			$form->prepare();
		
			echo $this->form()->openTag($form); ?>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('type')); ?>
				<?php echo $this->formInput($form->get('type')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('name')); ?>
				<?php echo $this->formInput($form->get('name')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<div class="form-group">
				<?php echo $this->formLabel($form->get('value')); ?>
				<?php echo $this->formInput($form->get('value')->setAttributes(array('class' => 'form-control'))); ?>
			</div>
			<hr />
			<?php echo $this->formHidden($form->get('settings_id')); ?>
			<?php echo $this->formSubmit($form->get('submit')->setAttributes(array('class' =>'btn btn-default'))); ?>
			<?php echo $this->formReset($form->get('reset')->setAttributes(array('class' =>'btn btn-default'))); ?>
		<?php echo $this->form()->closeTag($form); ?>
	</div>
</div>
