<pre class="debuginfo">
<strong>Module:</strong>     Admin\Settings &raquo;
<strong>Controller:</strong> <?php echo $this->controller ?> &raquo;
<strong>Action:</strong>     <?php echo $this->action ?>
</pre>

<div class="panel panel-default">
	<div class="panel-heading">
		<label>
			<span class="panel-title"><?php echo $this->translate("Einstellung bearbeiten"); ?></span>
		</label>
	</div>
	<div class="panel-body">
		<?php
			$form = $this->form;
			$form->setAttribute('action', $this->url(
			    'admin/settingsedit',
			    array(
			        'action'		=> 'edit',
			        'set_id'		=> $this->settings_id,
			    )
			));
			$form->prepare();
		
			echo $this->form()->openTag($form);
			echo $this->formHidden($form->get('settings_id'));
			echo $this->formRow($form->get('type'));
			echo $this->formRow($form->get('name'));
			echo $this->formRow($form->get('value'));
			echo '<hr />';
			echo $this->formSubmit($form->get('submit'));
			echo $this->formReset($form->get('reset'));
			echo $this->form()->closeTag();
		?>
	</div>
</div>
