<?php
namespace ApplicationTest\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2016-02-10 at 23:15:33.
 */
class CallbacksTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Callbacks
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Callbacks;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
    
    public function testFoo () {
    	$this->assertTrue(true);
    }
}
