<?php 
	/** @var \TwitterBootstrapAPI\View\Helper\Bootstrap $user **/
	$oBootstrap = $this->Bootstrap();
	/** @var \TwitterBootstrapAPI\View\Helper\Components $user **/
	$oComponents = $this->Components();
	/** @var \Admin\Entity\User $user **/
	$oUser = $this->zfcUserIdentity();
?>
<div class="clearfix"><?php 
	$body = $oComponents()->Void(array(
			'tagname'	=> 'div',
			'classnames'=> 'panel-body',
	))->setContent("<pre>".
		($oUser ? var_export( $oUser->getAclrole(), true ) : 'public') . PHP_EOL . 
		var_export( $this->isallowed('mvc:nouser'), true ) . PHP_EOL . 
		var_export( $this->isallowed('mvc:admin'), true ) . PHP_EOL .  
		var_export( $this->isdenied('mvc:nouser'), true ) . PHP_EOL . 
		var_export( $this->isdenied('mvc:admin'), true )
	."</pre>");
	$header = $oComponents()->Void( 
		array(
			'tagname'		=> 'div',
			'classnames'	=> 'panel-heading',
			'content'		=> array(
				'tagname'		=> 'h3',
				'classnames'	=> 'panel-title',
				'content'		=> 'debug display'
			)
		) 
	);
	$panel = $oComponents()->Panel()
		->setHeader( $header
		)
		->setContent( array(
			$body
		) )
	;
 	$panel->setTagname('section');
	echo $panel->render();
	
?></div>

<div class="clearfix"><?php echo $oComponents->Toolbar()->setContent("the toolbar content..."); ?></div>

<div class="clearfix"><?php echo $oComponents->Dashboard(); ?></div>

<div class="clearfix"><?php echo ($block = $oComponents->Block()
	->setHeader("Here come the header...")
	->setFooter("Here come the footer...")
	->render()
); ?></div>

<div class="clearfix"><?php echo $someContent = $oComponents()->Void(array(
	'tagname'	 => 'div',
	'class' => 'panel',
))->setContent("here comes some content..."); ?></div>
<div class="clearfix"><?php 

	$body = $oComponents()->Void(array(
			'tagname'	=> 'div',
			'classnames'=> 'panel-body',
	))->setContent("<em>content, content, content...</em>");
	
	$header = $oComponents()->Void( 
		array(
			'tagname'		=> 'div',
			'classnames'	=> 'panel-heading',
			'content'		=> array(
				'tagname'		=> 'h3',
				'classnames'	=> 'panel-title',
				'content'		=> 'my header...'
			)
		) 
	);
	$panel = $oComponents()->Panel()
		->setHeader( $header
		)
		->setContent( array(
			array(
				'tagname'		=> 'div',
				'classnames'	=> 'panel-body',
				'content'		=> 'here comes the widget content...'
			),
			array(
				'tagname'		=> 'div',
				'classnames'	=> 'panel-body',
				'content'		=> array(
					'<p>here comes more content...</p>',
					'<p>here comes more content...</p>',
					'<p><a id="xhrtest" class="fancybox.ajax" href="'.$this->url('application/default', array('controller' => 'index', 'action' => 'xhrtest', )).'">AJAX/XMLHTTPRequest test</a></p>',
					$someContent
				)
			),
			$body
		) )
		->setFooter( array(
			'tagname'		=> 'div',
			'classnames'	=> 'panel-footer',
			'content'		=> 'footer content...'
		) )
	;
	
 	$panel->setTagname('section');
	echo $panel->render();
	
?></div>

<div class="clearfix"><?php echo $oComponents->Nav(); ?></div>

<div class="clearfix"><?php echo $oComponents->Breadcrumbs(); ?></div>

<div class="clearfix"><?php echo $oComponents->Button(); ?></div>

<div class="clearfix"><?php echo $oComponents->ButtonGroup(); ?></div>


<?php //echo $oComponents->Void(); /* this really does nothing, it is just a view helper plugin default :D */ ?>
