<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title"><?php echo $this->translate('AJAX test') ?></h3>
    </div>
    <div class="panel-body">
        <p><?php echo sprintf($this->translate('AJAX test')); ?></p>
        <p><?php echo sprintf($this->translate('AJAX test')); ?></p>
        <p><?php echo sprintf($this->translate('AJAX test')); ?></p>
    </div>
</div>
