<?php
return array(
	'navigation' => array(
		'default' => array(
			array(
				'label' => 'Dashboard',
				'icon'	=> 'home',
				'route' => 'home',
				'pages'			=> array(
					array(
						'label'			=> 'Test-Page',
						'icon'			=> 'warning-sign',
						'route'			=> 'application/default',
						'controller' 	=> 'index',
						'action' 		=> 'test',
						'resource'		=> 'mvc:admin',
					),
				),
			),
			/*array(
				'label'			=> 'YourModule',
				'route' 		=> 'yourmodule/route',
				'controller'	=> 'your_index_controller_or_other',
				'action' 		=> 'your_index_action_or_other',
				'resource'		=> 'mvc:yourmodule.resource',
				'pages' => array(
					array(
						'label' 		=> 'YourModule Action/Item',
						'route' 		=> 'yourmodule/route',
						'resource'		=> 'mvc:yourmodule.resource',
						'controller'	=> 'your_controller',
						'action' 		=> 'your_action',
					),
				),
			),*/
			array(
				'label' => 'Account',
				'icon'	=> 'user',
				'route' => 'zfcuser',
				'badge' => array('type' => 'warning', 'value' => '!!!', 'title' => 'Remember to change your password after registration!'),
				'pages'			=> array(
					array(
						'label'			=> 'Login',
						'icon'			=> 'log-in',
						'route'			=> 'zfcuser/login',
						'resource'		=> 'mvc:nouser',
					),
					array(
						'label'			=> 'Registrierung',
						'icon'			=> 'link',
						'route'			=> 'zfcuser/register',
						'resource'		=> 'mvc:nouser',
					),
					array(
						'label'			=> 'E-Mail ändern',
						'icon'			=> 'envelope',
						'route'			=> 'zfcuser/changeemail',
						'resource'		=> 'mvc:user',
					),
					array(
						'label'			=> 'Passwort ändern',
						'icon'			=> 'lock',
						'route'			=> 'zfcuser/changepassword',
						'resource'		=> 'mvc:user',
					),
					array(
						'label'			=> 'Logout',
						'icon'			=> 'log-out',
						'route'			=> 'zfcuser/logout',
						'resource'		=> 'mvc:user',
					),
					array(
						'label'			=> 'Benutzer-Bestätigung',
						'route'			=> 'userconfirmation',
						'visible'		=> false,
					),
					array(
						'label'			=> 'Benutzer-Aktivierung',
						'route'			=> 'useractivation',
						'resource'		=> 'mvc:admin',
						'visible'		=> false,
					),
				),
			),
			array(
				'label'			=> 'Admin',
				'icon'			=> 'cog',
				'route'			=> 'admin',
				'resource'		=> 'mvc:admin',
				'pages'			=> array(
					array(
						'label'			=> 'Benutzer',
						'icon'			=> 'user',
						'route'			=> 'admin/default',
						'controller'	=> 'users',
						'resource'		=> 'mvc:admin',
						'pages'			=> array(
							array(
								'label'			=> 'Neu',
								'route'			=> 'admin/default',
								'controller'	=> 'users',
								'action' 		=> 'add',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Bearbeiten',
								'route'			=> 'admin/default',
								'controller'	=> 'users',
								'action' 		=> 'edit',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Entfernen',
								'route'			=> 'admin/default',
								'controller'	=> 'users',
								'action' 		=> 'delete',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
						),
					),
					array(
						'label' 		=> 'Rechte',
						'icon'			=> 'lock',
						'route'			=> 'admin/acledit',
						'action' 		=> 'index',
						'resource'		=> 'mvc:admin',
						'pages'			=> array(
							array(
								'label'			=> 'ACL',
								'icon'			=> 'asterisk',
								'route'			=> 'admin/acledit',
								'action' 		=> 'index',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Rollen',
								'icon'			=> 'user',
								'route'			=> 'admin/acledit',
								'action' 		=> 'roles',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
								'pages' => array(
									array(
										'label' 		=> 'Rolle hinzufügen',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'addrole',
									),
									array(
										'label' 		=> 'Rolle ändern',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'editrole',
									),
									array(
										'label' 		=> 'Rolle entfernen',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'deleterole',
									),
								),
							),
							array(
								'label'			=> 'Resourcen',
								'icon'			=> 'list-alt',
								'route'			=> 'admin/acledit',
								'action' 		=> 'resources',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
								'pages' => array(
									array(
										'label' 		=> 'Resource hinzufügen',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'addresource',
									),
									array(
										'label' 		=> 'Resource ändern',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'editresource',
									),
									array(
										'label' 		=> 'Resource entfernen',
										'route' 		=> 'admin/acledit',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'deleteresource',
									),
								),
							),
						),
					),
					array(
						'label' 		=> 'Einstellungen',
						'icon'			=> 'cog',
						'route'			=> 'admin/settingsedit',
						'action' 		=> 'index',
						'resource'		=> 'mvc:admin',
						'pages'			=> array(
							array(
								'label'			=> 'Neu',
								'route'			=> 'admin/settingsedit',
								'action' 		=> 'add',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Bearbeiten',
								'route'			=> 'admin/settingsedit',
								'action' 		=> 'edit',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Entfernen',
								'route'			=> 'admin/settingsedit',
								'action' 		=> 'delete',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
						),
					),
					array(
						'label'			=> 'System',
						'icon'			=> 'credit-card',
						'route'			=> 'system',
						'action'	    => 'index',
						'resource'		=> 'mvc:admin',
						'pages'			=> array(
							array(
								'label'			=> 'Systeminfo',
								'icon'			=> 'info-sign',
								'route'			=> 'system',
								'action' 		=> 'info',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Backup',
								'icon'			=> 'duplicate',
								'route'			=> 'system',
								'action' 		=> 'backup',
								'resource'		=> 'mvc:admin',
								'visible'		=> true,
							),
							array(
								'label'			=> 'Setup',
								'icon'			=> 'wrench',
								'route'			=> 'setup',
								'action' 		=> 'index',
								//'resource'		=> 'mvc:admin',
								'visible'		=> true,
								'pages' => array(
									array(
										'label' 		=> 'Installation',
										'route' 		=> 'setup',
										//'resource'		=> 'mvc:admin',
										'action' 		=> 'install',
									),
									array(
										'label' 		=> 'Update',
										'route' 		=> 'setup',
										'resource'		=> 'mvc:admin',
										'action' 		=> 'update',
									),
								),
							),
						),
					),
				),
			),
			array(
				'label'			=> 'Hilfe',
				'icon'			=> 'question-sign',
				'route'			=> 'application/default',
				'controller'	=> 'index',
				'action' 		=> 'notimplementedyet',
				'pages'			=> array(
					array(
						'label'			=> 'Hilfe',
						'icon'			=> 'question-sign',
						'route'			=> 'application/default',
						'controller'	=> 'index',
						'action' 		=> 'help',
					),
					array(
						'label'			=> 'Online-Support',
						'icon'			=> 'envelope',
						'route'			=> 'application/default',
						'controller'	=> 'index',
						'action' 		=> 'support',
					),
					array(
						'label' 		=> 'Über MyApplication',
						'icon'			=> 'info-sign',
						'route'			=> 'application/default',
						'controller'	=> 'index',
						'action' 		=> 'about',
					),
				),
			),
		),
	),
);